GET http://127.0.0.1:8000/api/userprofiles/1/friends/ HTTP/1.1
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTQwMTUyLCJpYXQiOjE2OTg1MDgxNTIsImp0aSI6IjAwMzA2ZjYzMjc5ZjQxYzJhZDk2ZmUyYmY2ZTQ2MDM5IiwidXNlcl9pZCI6Mn0.p-mr-WWUM8C4ghti7kRE0EkvghcXThexCX9PMEreGoc

###

GET http://127.0.0.1:8000/api/userprofiles/2/friends/gurugram HTTP/1.1
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTQwMTUyLCJpYXQiOjE2OTg1MDgxNTIsImp0aSI6IjAwMzA2ZjYzMjc5ZjQxYzJhZDk2ZmUyYmY2ZTQ2MDM5IiwidXNlcl9pZCI6Mn0.p-mr-WWUM8C4ghti7kRE0EkvghcXThexCX9PMEreGoc

###

GET http://localhost:8000/api/get_user_info/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTQwMTUyLCJpYXQiOjE2OTg1MDgxNTIsImp0aSI6IjAwMzA2ZjYzMjc5ZjQxYzJhZDk2ZmUyYmY2ZTQ2MDM5IiwidXNlcl9pZCI6Mn0.p-mr-WWUM8C4ghti7kRE0EkvghcXThexCX9PMEreGoc

###

POST http://localhost:8000/api/add_friend/mohit/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTU4NzUwLCJpYXQiOjE2OTg1MjY3NTAsImp0aSI6IjgxY2IwZGM5Mzk3NTQ2ZjRiYTU5MmIxZDQyNzIxZmQ2IiwidXNlcl9pZCI6MX0.hrsXHYEKDDOJabYAq53rAK3ltwXmyKTn1MUq1Pk4W4Q

###

POST http://localhost:8000/api/groups/create/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTU2NzcwLCJpYXQiOjE2OTg1MjQ3NzAsImp0aSI6IjkxOGU4NGI1Mzc4NjQwMTk4YzVjYWU3OGY1NjFmYTRlIiwidXNlcl9pZCI6Mn0.1zMqByrya842yZnZN0OC-WlwYk9LUS1_BxRmp8b_zAQ

{
    "name": "sample"
}

###

GET http://localhost:8000/api/groups/all/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTU2NzcwLCJpYXQiOjE2OTg1MjQ3NzAsImp0aSI6IjkxOGU4NGI1Mzc4NjQwMTk4YzVjYWU3OGY1NjFmYTRlIiwidXNlcl9pZCI6Mn0.1zMqByrya842yZnZN0OC-WlwYk9LUS1_BxRmp8b_zAQ


###

POST http://localhost:8000/api/groups/join/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTU4NzUwLCJpYXQiOjE2OTg1MjY3NTAsImp0aSI6IjgxY2IwZGM5Mzk3NTQ2ZjRiYTU5MmIxZDQyNzIxZmQ2IiwidXNlcl9pZCI6MX0.hrsXHYEKDDOJabYAq53rAK3ltwXmyKTn1MUq1Pk4W4Q

{
    "unique_code": "SV4ZIY"
}


###

POST http://localhost:8000/api/travel/update-travel/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTU4NzUwLCJpYXQiOjE2OTg1MjY3NTAsImp0aSI6IjgxY2IwZGM5Mzk3NTQ2ZjRiYTU5MmIxZDQyNzIxZmQ2IiwidXNlcl9pZCI6MX0.hrsXHYEKDDOJabYAq53rAK3ltwXmyKTn1MUq1Pk4W4Q

{
    "location": "New Location",
    "arrival_date": "2023-12-01",
    "departure_date": "2023-12-15",
    "available_dates": "2023-12-01, 2023-12-02, 2023-12-03"
}


###


GET http://localhost:8000/api/common-dates/calculate-common-dates/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTU4NzUwLCJpYXQiOjE2OTg1MjY3NTAsImp0aSI6IjgxY2IwZGM5Mzk3NTQ2ZjRiYTU5MmIxZDQyNzIxZmQ2IiwidXNlcl9pZCI6MX0.hrsXHYEKDDOJabYAq53rAK3ltwXmyKTn1MUq1Pk4W4Q




###
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTQwMTUyLCJpYXQiOjE2OTg1MDgxNTIsImp0aSI6IjAwMzA2ZjYzMjc5ZjQxYzJhZDk2ZmUyYmY2ZTQ2MDM5IiwidXNlcl9pZCI6Mn0.p-mr-WWUM8C4ghti7kRE0EkvghcXThexCX9PMEreGoc
