GET http://127.0.0.1:8000/api/userprofiles/1/friends/ HTTP/1.1
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTQwMTUyLCJpYXQiOjE2OTg1MDgxNTIsImp0aSI6IjAwMzA2ZjYzMjc5ZjQxYzJhZDk2ZmUyYmY2ZTQ2MDM5IiwidXNlcl9pZCI6Mn0.p-mr-WWUM8C4ghti7kRE0EkvghcXThexCX9PMEreGoc

###

GET http://127.0.0.1:8000/api/userprofiles/2/friends/noida HTTP/1.1
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTM0OTgyLCJpYXQiOjE2OTg1MDI5ODIsImp0aSI6ImNlZDdkYTE4NzcxYTQ3ZDViZjMzYjVkZWYyNjhiMzE3IiwidXNlcl9pZCI6N30.McJ3URhWRrI3SpEqgJm3IFWW77epXFmtfS68rDEUH7w
###

GET http://localhost:8000/api/get_user_info/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTQwMTUyLCJpYXQiOjE2OTg1MDgxNTIsImp0aSI6IjAwMzA2ZjYzMjc5ZjQxYzJhZDk2ZmUyYmY2ZTQ2MDM5IiwidXNlcl9pZCI6Mn0.p-mr-WWUM8C4ghti7kRE0EkvghcXThexCX9PMEreGoc

###

POST http://localhost:8000/api/add_friend/mohit/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTU4NzUwLCJpYXQiOjE2OTg1MjY3NTAsImp0aSI6IjgxY2IwZGM5Mzk3NTQ2ZjRiYTU5MmIxZDQyNzIxZmQ2IiwidXNlcl9pZCI6MX0.hrsXHYEKDDOJabYAq53rAK3ltwXmyKTn1MUq1Pk4W4Q

###

POST http://localhost:8000/api/groups/create/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTU2NzcwLCJpYXQiOjE2OTg1MjQ3NzAsImp0aSI6IjkxOGU4NGI1Mzc4NjQwMTk4YzVjYWU3OGY1NjFmYTRlIiwidXNlcl9pZCI6Mn0.1zMqByrya842yZnZN0OC-WlwYk9LUS1_BxRmp8b_zAQ

{
    "name": "sample"
}

###

GET http://localhost:8000/api/groups/all/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTU2NzcwLCJpYXQiOjE2OTg1MjQ3NzAsImp0aSI6IjkxOGU4NGI1Mzc4NjQwMTk4YzVjYWU3OGY1NjFmYTRlIiwidXNlcl9pZCI6Mn0.1zMqByrya842yZnZN0OC-WlwYk9LUS1_BxRmp8b_zAQ


###

POST http://localhost:8000/api/groups/join/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTU4NzUwLCJpYXQiOjE2OTg1MjY3NTAsImp0aSI6IjgxY2IwZGM5Mzk3NTQ2ZjRiYTU5MmIxZDQyNzIxZmQ2IiwidXNlcl9pZCI6MX0.hrsXHYEKDDOJabYAq53rAK3ltwXmyKTn1MUq1Pk4W4Q

{
    "unique_code": "SV4ZIY"
}


###

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTQwMTUyLCJpYXQiOjE2OTg1MDgxNTIsImp0aSI6IjAwMzA2ZjYzMjc5ZjQxYzJhZDk2ZmUyYmY2ZTQ2MDM5IiwidXNlcl9pZCI6Mn0.p-mr-WWUM8C4ghti7kRE0EkvghcXThexCX9PMEreGoc
