# Generated by Django 4.2.6 on 2023-10-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='available_dates',
        ),
        migrations.AlterField(
            model_name='travel',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='AvailableDate',
        ),
        migrations.AddField(
            model_name='travel',
            name='available_dates',
            field=models.TextField(default=29102023),
            preserve_default=False,
        ),
    ]
